### USUÁRIOS

### Listar todos os usuários
GET http://localhost:3000/usuarios

###

### Criar usuário
POST http://localhost:3000/usuarios
content-type: application/json

{
    "nome": "Grazi",
    "tipo": "Farmacêutico",
    "email": "grazi@gmail.com",
    "senha": "senha123"
}

###

### login usuário
POST http://localhost:3000/usuarios/login
content-type: application/json

{
    "email": "grazi@gmail.com",
    "senha": "senha123"
}

###

### Tipo usuário
GET http://localhost:3000/usuarios/tipo/Farmacêutico


### Buscar usuários por nome (retorna lista)
GET http://localhost:3000/usuarios/buscar?nome=Grazi

###

### Buscar usuários por email (retorna lista)
GET http://localhost:3000/usuarios/buscar?email=grazi@gmail.com

### MEDICAMENTOS

### Criar/cadastrar Medicamentos
POST http://localhost:3000/medicamentos
content-type: application/json

{
 "nomeMedicamento": "nomeMedicamento",
 "estoque": "estoque",
 "informacoes": "informacoes"
}

### Criar/cadastrar Medicamentos
GET http://localhost:3000/medicamentos


### Buscar medicamento por id e mensagem de erro se não achar 
GET http://localhost:3000/medicamentos/1a5216b5-1f77-4255-9d88-43b7c35ea45c

### Dar baixa no estoque do medicamento pelo id do mesmo
GET http://localhost:3000/medicamentos/:id

### Status do estoque
GET http://localhost:3000/medicamentos/status


###SOLICITAÇÃO

### Status de erro ao buscar solicitações
GET http://localhost:3000/solicitacoes

###Criar Solicitação
POST http://localhost:3000/solicitacoes
content-type: application/json

{
  "nomePaciente": "joao",
  "idadePaciente": "20",
  "medicoId": "oi",
  "medicamentoId": "oi",
  "descricaoPaciente": "Dor e Febre",
  "status": "pendentes",
  "farmaceuticoId": "oi"

}

### Status ao buscar solicitações pendentes
GET http://localhost:3000/solicitacoes/pendentes

### Status ao buscar solicitações por nome do paciente
GET http://localhost:3000/solicitacoes/paciente/joao

### Atualização de status da solicitação
PUT http://localhost:3000/solicitacoes/2ad52bd9-96d3-4762-b702-be5c498f6cf7/status
content-type: application/json

{
  "novoStatus": "Aprovada",
  "farmaceuticoId": "oi"
}
